apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: xxx
spec:
  ports:
    - port: 9000
  selector:
    app: wordpress
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: xxx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: ClusterIP
