version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    environment:
      TEST_ENV: TESTENV123
    volumes:
      -  ./content:/usr/share/nginx/html:ro
      -  ./default.conf:/etc/nginx/conf.d/default.conf:ro
      -  ./nginx.conf:/etc/nginx/nginx.conf:ro